### ISSUE TITLE
Support gossipsub 1.2.0

### ISSUE THREAD

**Issue by arnetheduck** [vacp2p/nim-libp2p#1102]
https://github.com/libp2p/specs/pull/548 - this has been merged and IDONTWANT is officially part of the spec - the feature is formally only enabled in gossipsub 1.2.0, meaning we must start supporting that version as a protocol in order to receive IDONTWANT messages from other clients (putting the fields in 1.1 was a hack).

**Comment by diegomrsantos** [comment]
Is it enough to create a new version here https://github.com/vacp2p/nim-libp2p/blob/0911cb20f4a0b880451938988f24cb077cfd8b1b/libp2p/protocols/pubsub/gossipsub/types.nim#L22 and add it here https://github.com/vacp2p/nim-libp2p/blob/0911cb20f4a0b880451938988f24cb077cfd8b1b/libp2p/protocols/pubsub/gossipsub.nim#L197 ?

**Comment by ufarooqstatus** [comment]
[Gossipsub-v1.2 specification]( https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.2.md?plain=1#L81-L82) suggest that we MAY cancel outstanding IWANT if we receive the message from some other peer 

[This specification]( https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.2.md?plain=1#L83) also suggests that we SHOULD cancel any queued IWANT reply if we receive IDONTWANT from the requesting peer. IMO, we have this available in this [draft PR]( https://github.com/vacp2p/nim-libp2p/pull/1100/files#diff-cd23f9cd2a0f9c037ef0b4245ee7d06c09a24985c8ee5ed39fff496f705570c3R349-R352)
