### ISSUE TITLE
transport interoperability tests is failing

### ISSUE THREAD

**Issue by diegomrsantos** [vacp2p/nim-libp2p#1158]

**Comment by AlejandroCabeza** [comment]
We have applied a quick fix that allows the tests to work again. 
They do considerably take more time to finish, but we are working on fixing that right now.

**Comment by AlejandroCabeza** [comment]
This issue has been superseded by https://github.com/vacp2p/nim-libp2p/issues/1158

**Comment by diegomrsantos** [comment]
> We have applied a quick fix that allows the tests to work again.

This quick fix needs to be removed.

**Comment by AlejandroCabeza** [comment]
> > We have applied a quick fix that allows the tests to work again.
> 
> This quick fix needs to be removed.

Would you mind creating a different issue for this so we can track and prioritise it properly during weeklies?
