### ISSUE TITLE
`libp2p/crypto/minasn1.nim` doesn't build on Nim `version-2-2`/`devel`

### ISSUE THREAD

**Issue by tersec** [vacp2p/nim-libp2p#1194]
https://github.com/nim-lang/Nim/issues/24125

Not a terribly high-priority bug, but worth documenting here so no one else spends time hunting down the root cause of this.

The specific error one gets is:
```
nim-libp2p/libp2p/crypto/minasn1.nim(392, 36) Error: type mismatch
Expression: safeConvert[int](b)
  [1] b: byte

Expected one of (first mismatch at [position]):
[2] template safeConvert[T: SomeInteger; S: Ordinal](value: S): T
  missing generic parameter: S
```
and apparently was an accident it worked at all.

**Comment by tersec** [comment]
> Thanks for reporting it. Could you please explain why it was an accident it worked at all?

Araq in https://github.com/nim-lang/Nim/issues/24125#issuecomment-2354530627 notes:
> Partial explicit generic instantations are not in the language spec.

**Comment by diegomrsantos** [comment]
What would you recommend here? I'm not sure this proc is necessary.

**Comment by tersec** [comment]
```nim
template safeConvert*[T: SomeInteger](value: SomeOrdinal): T =
  ## Converts `value` from S to `T` iff `value` is guaranteed to be preserved.
  when int64(T.low) <= int64(typeof(value).low()) and
       uint64(T.high) >= uint64(typeof(value).high):
    T(value)
  else:
    {.error: "Source and target types have an incompatible range low..high".}
```
for example
