### ISSUE TITLE
peerStore[AddressBook] missing remote endpoints of established connection.

### ISSUE THREAD

**Issue by cheatfate** [vacp2p/nim-libp2p#1210]
Current version of peerStore[AddressBook] holds only addresses which was announced by the peer itself during `identify` phase, but did not holds remote peer address of currently established connections.
For example `nim-libp2p` holds this data for fully connected peer via Internet. 
```
/ip4/10.81.2.114/tcp/32502, /ip4/127.0.0.1/tcp/32502, /ip4/10.81.2.114/udp/32503/quic-v1, /ip4/127.0.0.1/udp/32503/quic-v1
```
As you can see there is no globally routable IP addresses available, which i think is incorrect.

**Comment by diegomrsantos** [comment]
This can be achieved using https://github.com/vacp2p/nim-libp2p/blob/dc83a1e9b68f00b3be7e09febdb1a3f877321b9a/libp2p/stream/connection.nim#L35

**Comment by cheatfate** [comment]
`Connection` object is easily accessible and needs to be accounted in `nimbus-eth2` to properly access this value, its an overhead for application, imho. This functionality should be accessible via `peerStore`.
